spring.application.name=SmtpEmail

app.email.cleanup.retention-hours=1

backend.base.url=${BACKEND_BASE_URL}

# -------------------------
# DATASOURCE (Postgres)
# -------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# -------------------------
# JPA / Hibernate
# -------------------------
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL}
spring.jpa.properties.hibernate.jdbc.time_zone=${SPRING_JPA_TIMEZONE}

# -------------------------
# SERVER
# -------------------------
server.port=${SERVER_PORT}
frontend.url=${FRONTEND_URL}
# -------------------------
# SMTP / EMAIL
# -------------------------
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000