services:
  # -------------------------
  # Banco de dados
  # -------------------------
  db:
    image: postgres:15
    container_name: streampix-postgres
    restart: always
    environment:
      POSTGRES_USER: streampix_user
      POSTGRES_PASSWORD: 87Y87WEYTF87C7834RYN
      POSTGRES_DB: streampix_db
    volumes:
      - ./streampix-db/data:/var/lib/postgresql/data
    networks:
      - streampix-net
    ports:
      - "5434:5432"

  

  # -------------------------
  # Backend Spring Boot
  # -------------------------
  backend:
    build:
      context: ./streampix-backend
      dockerfile: Dockerfile
    container_name: streampix-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - "streampix-backend/.env"
    depends_on:
      - db
      - tts
    networks:
      - streampix-net

  # -------------------------
  # TTS FastAPI
  # -------------------------
  tts:
    build:
      context: ./streampix-tts
      dockerfile: Dockerfile
    container_name: streampix-tts
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - "streampix-tts/.env"
    networks:
      - streampix-net

# -------------------------
# Rede interna
# -------------------------
networks:
  streampix-net:
    driver: bridge
